---
title: "Citation model summaries"
author: "Luke Maurits"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(brms)
library(matrixStats)

m_null <- readRDS("m_citations_null.rds") %>% add_criterion("loo")
m_education <- readRDS("m_citations_singpred_education_shape.rds") %>% add_criterion("loo")
m_industry <- readRDS("m_citations_singpred_industry_shape.rds") %>% add_criterion("loo")
m_gdp <- readRDS("m_citations_singpred_gdp_shape.rds") %>% add_criterion("loo")
m_democracy <- readRDS("m_citations_singpred_democracy_shape.rds") %>% add_criterion("loo")
m_household_size <- readRDS("m_citations_singpred_household_size_shape.rds") %>% add_criterion("loo")
m_urbanism <- readRDS("m_citations_singpred_urbanism_shape.rds") %>% add_criterion("loo")
m_gini <- readRDS("m_citations_singpred_gini_shape.rds") %>% add_criterion("loo")
m_religiosity <- readRDS("m_citations_singpred_religiosity_shape.rds") %>% add_criterion("loo")
m_ethfrac <- readRDS("m_citations_singpred_ethfrac_shape.rds") %>% add_criterion("loo")
```

## Null model
```{r}
fixef(m_null)
```

## Single predictor models

```{r}
pred_table <- function(m, varname) {
	nd <- expand_grid(x=1:10, multi_country=0.5, exposure=10)
	colnames(nd) <- c(varname, "multi_country", "exposure")
	true_preds <- posterior_epred(m, newdata=nd, re_formula=NA)
	nd$multi_country <- -0.5
	false_preds <- posterior_epred(m, newdata=nd, re_formula=NA)
	contrast <- true_preds - false_preds
	nd$diff_posterior_mean <- colMeans(contrast)
	nd$diff_ci_lower <- colQuantiles(contrast, probs=0.025)
	nd$diff_ci_upper <- colQuantiles(contrast, probs=0.975)
	return(select(nd, -multi_country, -exposure))
}

micro_summary <- function(x, cond, var) {
	a <- mean(x)
	b <- quantile(x, p=0.025)
	c <- quantile(x, p=0.975)
	return(paste(str_pad(paste(cond, var), 24, "right"), round(a, 4), round(b, 4), round(c, 4)))
}

```

### Education model

```{r echo=FALSE}
fixef(m_education)
x <- as_draws_df(m_education)
multi_country_effect <- as_vector(x[,5]) + 0.5*as_vector(x[,6])
mono_country_effect <- as_vector(x[,5]) - 0.5*as_vector(x[,6])
micro_summary(multi_country_effect, "multi-country effect of", "education")
micro_summary(mono_country_effect, "mono-country effect of", "education")
pred_table(m_education, "education")
```

### Industry model

```{r echo=FALSE}
fixef(m_industry)
x <- as_draws_df(m_industry)
multi_country_effect <- as_vector(x[,5]) + 0.5*as_vector(x[,6])
mono_country_effect <- as_vector(x[,5]) - 0.5*as_vector(x[,6])
micro_summary(multi_country_effect, "multi-country effect of", "industry")
micro_summary(mono_country_effect, "mono-country effect of", "industry")
pred_table(m_industry, "industry")
```

### GDP model

```{r echo=FALSE}
fixef(m_gdp)
x <- as_draws_df(m_gdp)
multi_country_effect <- as_vector(x[,5]) + 0.5*as_vector(x[,6])
mono_country_effect <- as_vector(x[,5]) - 0.5*as_vector(x[,6])
micro_summary(multi_country_effect, "multi-country effect of", "gdp")
micro_summary(mono_country_effect, "mono-country effect of", "gdp")
pred_table(m_gdp, "gdp")
```

### Democracy model

```{r echo=FALSE}
fixef(m_democracy)
x <- as_draws_df(m_democracy)
multi_country_effect <- as_vector(x[,5]) + 0.5*as_vector(x[,6])
mono_country_effect <- as_vector(x[,5]) - 0.5*as_vector(x[,6])
micro_summary(multi_country_effect, "multi-country effect of", "democracy")
micro_summary(mono_country_effect, "mono-country effect of", "democracy")
pred_table(m_democracy, "democracy")
```

### Household size model

```{r echo=FALSE}
fixef(m_household_size)
x <- as_draws_df(m_household_size)
multi_country_effect <- as_vector(x[,5]) + 0.5*as_vector(x[,6])
mono_country_effect <- as_vector(x[,5]) - 0.5*as_vector(x[,6])
micro_summary(multi_country_effect, "multi-country effect of", "household_size")
micro_summary(mono_country_effect, "mono-country effect of", "household_size")
pred_table(m_household_size, "household_size")
```

### Urbanism model

```{r echo=FALSE}
fixef(m_urbanism)
x <- as_draws_df(m_urbanism)
multi_country_effect <- as_vector(x[,5]) + 0.5*as_vector(x[,6])
mono_country_effect <- as_vector(x[,5]) - 0.5*as_vector(x[,6])
micro_summary(multi_country_effect, "multi-country effect of", "urbanism")
micro_summary(mono_country_effect, "mono-country effect of", "urbanism")
pred_table(m_urbanism, "urbanism")
```

### GINI model

```{r echo=FALSE}
fixef(m_gini)
x <- as_draws_df(m_gini)
multi_country_effect <- as_vector(x[,5]) + 0.5*as_vector(x[,6])
mono_country_effect <- as_vector(x[,5]) - 0.5*as_vector(x[,6])
micro_summary(multi_country_effect, "multi-country effect of", "gini")
micro_summary(mono_country_effect, "mono-country effect of", "gini")
pred_table(m_gini, "gini")
```

### Religiosity model

```{r echo=FALSE}
fixef(m_religiosity)
x <- as_draws_df(m_religiosity)
multi_country_effect <- as_vector(x[,5]) + 0.5*as_vector(x[,6])
mono_country_effect <- as_vector(x[,5]) - 0.5*as_vector(x[,6])
micro_summary(multi_country_effect, "multi-country effect of", "religiosity")
micro_summary(mono_country_effect, "mono-country effect of", "religiosity")
pred_table(m_religiosity, "religiosity")
```

### Ethnic diversity model

```{r echo=FALSE}
fixef(m_ethfrac)
x <- as_draws_df(m_ethfrac)
multi_country_effect <- as_vector(x[,5]) + 0.5*as_vector(x[,6])
mono_country_effect <- as_vector(x[,5]) - 0.5*as_vector(x[,6])
micro_summary(multi_country_effect, "multi-country effect of", "ethfrac")
micro_summary(mono_country_effect, "mono-country effect of", "ethfrac")
pred_table(m_ethfrac, "ethfrac")
```

### Comparisons

```{r echo=FALSE}
knitr::kable(loo_compare(m_null, m_democracy), digits=2)
knitr::kable(loo_compare(m_null, m_education), digits=2)
knitr::kable(loo_compare(m_null, m_industry), digits=2)
knitr::kable(loo_compare(m_null, m_gdp), digits=2)
knitr::kable(loo_compare(m_null, m_gini), digits=2)
knitr::kable(loo_compare(m_null, m_ethfrac), digits=2)
knitr::kable(loo_compare(m_null, m_household_size), digits=2)
knitr::kable(loo_compare(m_null, m_religiosity), digits=2)
knitr::kable(loo_compare(m_null, m_urbanism), digits=2)
```
